import type { PlaybookRule } from "../types";

export const DEFAULT_PLAYBOOK: PlaybookRule[] = [
  {
    id: "liability-cap",
    clauseCategory: "liability",
    preferred: "Liability capped at 100% of fees paid in the preceding 12 months.",
    acceptable: "Liability capped at 200% of fees paid in the preceding 12 months.",
    fallback: "Liability capped at the greater of RM 500,000 or fees paid.",
    walkAway: "Unlimited liability or liability not capped.",
    rationale: "Caps align with our standard risk envelope and insurance coverage.",
    escalationPolicy: "Escalate to CFO if cap exceeds 200% of fees.",
  },
  {
    id: "indemnity",
    clauseCategory: "indemnity",
    preferred: "Mutual indemnity limited to third-party claims arising from gross negligence or wilful misconduct.",
    acceptable: "One-way indemnity limited to third-party claims, capped and subject to a claims notice.",
    fallback: "One-way indemnity subject to a monetary cap equal to the liability cap.",
    walkAway: "Indemnity for consequential or indirect losses, or uncapped.",
    rationale: "We accept indemnity risk only when bounded.",
    escalationPolicy: "Escalate to GC if fallback position is required.",
  },
  {
    id: "termination",
    clauseCategory: "termination",
    preferred: "Either party may terminate for convenience on 60 days' written notice.",
    acceptable: "Either party may terminate for convenience on 90 days' written notice.",
    fallback: "Termination for convenience only by counterparty on 120 days' notice.",
    walkAway: "No termination for convenience, or lock-in exceeding 24 months.",
    rationale: "We need exit optionality at every stage.",
  },
  {
    id: "payment",
    clauseCategory: "payment",
    preferred: "Invoices due 30 days from receipt, interest at 1% per month on overdue amounts.",
    acceptable: "Invoices due 45 days from receipt.",
    fallback: "Invoices due 60 days from receipt with late interest.",
    walkAway: "Payment beyond 90 days or no late interest.",
    rationale: "Cash flow protection.",
  },
  {
    id: "data-protection",
    clauseCategory: "data-protection",
    preferred: "Mutual compliance with PDPA; processing only on documented instructions; breach notice within 24 hours.",
    acceptable: "Mutual compliance with PDPA; breach notice within 72 hours.",
    fallback: "Compliance with applicable data protection laws; breach notice within 7 days.",
    walkAway: "No data protection clause, or transfer of data outside permitted jurisdictions without safeguards.",
    rationale: "Regulatory exposure under PDPA 2010.",
    escalationPolicy: "Escalate to DPO.",
  },
  {
    id: "ip",
    clauseCategory: "intellectual-property",
    preferred: "Each party retains its background IP; foreground IP jointly owned with mutual licensing.",
    acceptable: "Foreground IP owned by the party that develops it, with perpetual licence to the other.",
    fallback: "Foreground IP owned by us, with a broad licence to the counterparty.",
    walkAway: "Transfer of our background IP or assignment of foreground IP without compensation.",
    rationale: "Protects our core IP portfolio.",
  },
  {
    id: "governing-law",
    clauseCategory: "governing-law",
    preferred: "Governing law of Malaysia; exclusive jurisdiction of the courts of Kuala Lumpur.",
    acceptable: "Governing law of Malaysia; arbitration under AIAC rules, seat in Kuala Lumpur.",
    fallback: "Governing law of Singapore; SIAC arbitration.",
    walkAway: "Governing law outside common law jurisdictions.",
    rationale: "Predictable dispute resolution.",
  },
  {
    id: "dispute-resolution",
    clauseCategory: "dispute-resolution",
    preferred: "Negotiation → mediation → arbitration under AIAC rules, seat in Kuala Lumpur, single arbitrator.",
    acceptable: "Negotiation → arbitration under AIAC rules.",
    fallback: "Arbitration under SIAC rules.",
    walkAway: "Litigation in counterparty's home jurisdiction.",
    rationale: "Time and cost certainty.",
  },
  {
    id: "confidentiality",
    clauseCategory: "confidentiality",
    preferred: "Mutual confidentiality with standard exclusions, 3-year survival post-termination.",
    acceptable: "Mutual confidentiality, 5-year survival.",
    fallback: "One-way confidentiality in our favour, 5-year survival.",
    walkAway: "No confidentiality, or indefinite survival exceeding 10 years.",
    rationale: "Standard commercial practice.",
  },
  {
    id: "force-majeure",
    clauseCategory: "force-majeure",
    preferred: "Standard force majeure with carve-out for payment obligations; termination right after 60 days.",
    acceptable: "Force majeure with termination right after 90 days.",
    fallback: "Narrow force majeure limited to catastrophic events.",
    walkAway: "Force majeure covering foreseeable events (e.g., change of law, labour disputes).",
    rationale: "Avoids open-ended suspension.",
  },
];
