allowBuilds:
  '@prisma/engines': true
  '@tensorflow/tfjs-node': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@ai-sdk/deepinfra@3.0.42'
  - '@ai-sdk/openai-compatible@3.0.42'
  - '@ai-sdk/provider-utils@5.0.35'
  - '@ai-sdk/provider@4.0.10'
