declare module 'lucide-react' {
  export type LucideIcon = any
  export type LucideProps = Record<string, any>

  export const Activity: any
  export const AlarmClock: any
  export const AlertCircle: any
  export const AlertOctagon: any
  export const AlertTriangle: any
  export const AlertTriangleIcon: any
  export const Archive: any
  export const ArrowDown: any
  export const ArrowDownAZ: any
  export const ArrowDownRight: any
  export const ArrowDownToLine: any
  export const ArrowLeft: any
  export const ArrowLeftIcon: any
  export const ArrowRight: any
  export const ArrowRightIcon: any
  export const ArrowUp: any
  export const ArrowUpRight: any
  export const BarChart3: any
  export const Bell: any
  export const BookIcon: any
  export const BookMarked: any
  export const BookOpen: any
  export const BookTemplate: any
  export const Bookmark: any
  export const BookmarkCheck: any
  export const BookmarkIcon: any
  export const BookmarkPlus: any
  export const Bot: any
  export const BotIcon: any
  export const Boxes: any
  export const Brain: any
  export const BrainCircuit: any
  export const BrainIcon: any
  export const Briefcase: any
  export const Building: any
  export const Building2: any
  export const Calculator: any
  export const Calendar: any
  export const CalendarClock: any
  export const CalendarDays: any
  export const Camera: any
  export const Check: any
  export const CheckCircle: any
  export const CheckCircle2: any
  export const CheckCircle2Icon: any
  export const CheckCircleIcon: any
  export const CheckIcon: any
  export const CheckSquare: any
  export const ChevronDown: any
  export const ChevronDownIcon: any
  export const ChevronLeft: any
  export const ChevronLeftIcon: any
  export const ChevronRight: any
  export const ChevronRightIcon: any
  export const ChevronUpIcon: any
  export const ChevronsUpDownIcon: any
  export const Circle: any
  export const CircleAlert: any
  export const CircleCheckIcon: any
  export const CircleDashed: any
  export const CircleDollarSign: any
  export const CircleDotIcon: any
  export const CircleHelp: any
  export const CircleIcon: any
  export const CircleSmallIcon: any
  export const ClipboardList: any
  export const Clock: any
  export const Clock3: any
  export const ClockIcon: any
  export const Code: any
  export const Coins: any
  export const Command: any
  export const Copy: any
  export const CopyIcon: any
  export const Cpu: any
  export const Crown: any
  export const Database: any
  export const DollarSign: any
  export const DotIcon: any
  export const Download: any
  export const Edit3: any
  export const ExternalLink: any
  export const ExternalLinkIcon: any
  export const Eye: any
  export const EyeIcon: any
  export const EyeOff: any
  export const EyeOffIcon: any
  export const File: any
  export const FileCheck: any
  export const FileCheck2: any
  export const FileIcon: any
  export const FileJson: any
  export const FilePlus2: any
  export const FileQuestion: any
  export const FileSearch: any
  export const FileSignature: any
  export const FileText: any
  export const FileTextIcon: any
  export const FileType: any
  export const Filter: any
  export const FlaskConical: any
  export const Folder: any
  export const FolderIcon: any
  export const FolderInput: any
  export const FolderOpen: any
  export const FolderOpenIcon: any
  export const FolderTree: any
  export const Gavel: any
  export const GitBranch: any
  export const GitCommitIcon: any
  export const GitCompare: any
  export const Globe: any
  export const Globe2: any
  export const GlobeIcon: any
  export const Grid3x3: any
  export const Heart: any
  export const HelpCircle: any
  export const History: any
  export const Home: any
  export const ImageIcon: any
  export const Inbox: any
  export const Info: any
  export const InfoIcon: any
  export const Key: any
  export const KeyRound: any
  export const Keyboard: any
  export const Landmark: any
  export const Languages: any
  export const Laptop: any
  export const Layers: any
  export const LayoutDashboard: any
  export const LayoutGrid: any
  export const LayoutTemplate: any
  export const Leaf: any
  export const Library: any
  export const LifeBuoy: any
  export const Lightbulb: any
  export const Link: any
  export const Link2: any
  export const List: any
  export const ListChecks: any
  export const ListTodo: any
  export const Loader: any
  export const Loader2: any
  export const Loader2Icon: any
  export const LoaderIcon: any
  export const Lock: any
  export const LogOut: any
  export const Mail: any
  export const MapPin: any
  export const MarsIcon: any
  export const MarsStrokeIcon: any
  export const Maximize2: any
  export const Menu: any
  export const MessageCircleIcon: any
  export const MessageSquare: any
  export const MessageSquareQuote: any
  export const MessageSquareText: any
  export const MicIcon: any
  export const Minus: any
  export const MinusCircle: any
  export const MinusIcon: any
  export const Monitor: any
  export const Moon: any
  export const MoreHorizontal: any
  export const MoreHorizontalIcon: any
  export const Music2Icon: any
  export const Network: any
  export const NonBinaryIcon: any
  export const OctagonXIcon: any
  export const PackageIcon: any
  export const Palette: any
  export const PanelLeftClose: any
  export const PanelLeftIcon: any
  export const PanelLeftOpen: any
  export const PanelRight: any
  export const PanelRightClose: any
  export const PanelRightOpen: any
  export const Paperclip: any
  export const PaperclipIcon: any
  export const Pause: any
  export const PauseCircle: any
  export const PauseIcon: any
  export const PenLine: any
  export const Phone: any
  export const Pin: any
  export const Play: any
  export const PlayCircle: any
  export const PlayIcon: any
  export const Plug: any
  export const Plus: any
  export const PlusIcon: any
  export const Printer: any
  export const Quote: any
  export const Radar: any
  export const Receipt: any
  export const RefreshCw: any
  export const RotateCcw: any
  export const Rows3: any
  export const Save: any
  export const Scale: any
  export const Scale3D: any
  export const ScrollText: any
  export const Search: any
  export const SearchIcon: any
  export const Send: any
  export const SendIcon: any
  export const Server: any
  export const Settings: any
  export const Settings2: any
  export const Share2: any
  export const Shield: any
  export const ShieldAlert: any
  export const ShieldCheck: any
  export const ShieldQuestion: any
  export const ShieldX: any
  export const Skull: any
  export const SlidersHorizontal: any
  export const Smartphone: any
  export const Sparkles: any
  export const Square: any
  export const SquareIcon: any
  export const Star: any
  export const Sun: any
  export const Swords: any
  export const Table2: any
  export const TerminalIcon: any
  export const TimerOff: any
  export const TransgenderIcon: any
  export const Trash2: any
  export const Trash2Icon: any
  export const TrendingDown: any
  export const TrendingUp: any
  export const TriangleAlert: any
  export const TriangleAlertIcon: any
  export const Trophy: any
  export const Upload: any
  export const UploadCloud: any
  export const User: any
  export const UserCheck: any
  export const UserPlus: any
  export const UserRound: any
  export const Users: any
  export const VenusAndMarsIcon: any
  export const VenusIcon: any
  export const VideoIcon: any
  export const Wand2: any
  export const Webhook: any
  export const Workflow: any
  export const Wrench: any
  export const WrenchIcon: any
  export const X: any
  export const XCircle: any
  export const XCircleIcon: any
  export const XIcon: any
  export const Zap: any
  export const ZoomIn: any
  export const ZoomOut: any
}
