// runners/index.js
module.exports = {
  ...require('./openclaw'),
  ...require('./autogpt'),
  ...require('./claude-code'),
  ...require('./claude-desktop'),
  ...require('./codex'),
  ...require('./cursor'),
  ...require('./fable'),
  ...require('./gemini-cli'),
  ...require('./hermes'),
  ...require('./kiro'),
  ...require('./local-coder'),
  ...require('./loop-service-adapter'),
  ...require('./registry'),
  ...require('./dispatchViaRegistry'),
  ...require('./capabilityRouting'),
  ...require('./reputationAssign'),
  ...require('./reputationPreference'),
  ...require('./trustPresets'),
  ...require('./types'),
};
