import type {
  AppNotification,
  AIUsage,
  ComposerContext,
  Conversation,
  DashboardMetrics,
  Document,
  DocumentAnalysis,
  Draft,
  LegalArea,
  LegalSource,
  LegalTask,
  Matter,
  MatterStatus,
  Message,
  PromptSuggestion,
  RecentActivity,
  ResearchResult,
  RiskCategory,
  RiskItem,
  SavedItem,
  ToolExecution,
  User,
} from "@/types/lawmate";


// Module-level mock data must not call `Date.now()` because that drifts between
// SSR and client render → React hydration mismatch (server rendered "4m ago"
// while client rendered "just now"). The mock timestamps are fake by definition,
// so we anchor them to a fixed reference epoch. The relative-time display
// buckets in days/hours, so a stable offset is visually correct.
const MOCK_NOW = new Date('2026-09-01T22:00:00.000Z');
const now = () => MOCK_NOW.toISOString();
const isoDaysFromNow = (d: number) =>
  new Date(MOCK_NOW.getTime() + d * 86400000).toISOString();

export const MOCK_USER: User = {
  id: "u-001",
  name: "Aisyah Rahman",
  email: "aisyah@lawmate.ai",
  role: "lawyer",
  organisation: "Rahman & Partners",
};

export const PROMPT_SUGGESTIONS: PromptSuggestion[] = [
  {
    id: "s1",
    label: "Review this employment clause",
    prompt: "Review the attached employment clause for risks and compliance with Malaysian employment law.",
    category: "review",
  },
  {
    id: "s2",
    label: "Explain this section in plain English",
    prompt: "Explain the following section of the Act in plain English and list the practical implications.",
    category: "research",
  },
  {
    id: "s3",
    label: "Is this hostel rule legally compliant?",
    prompt: "Assess whether this hostel rule is compliant with Malaysian housing and tenancy regulations.",
    category: "review",
  },
  {
    id: "s4",
    label: "Find potential legal risks",
    prompt: "Identify potential legal risks in the attached document, with severity and recommended mitigation.",
    category: "analyse",
  },
  {
    id: "s5",
    label: "Compare these two documents",
    prompt: "Compare the two attached documents and summarise the key differences in obligations and risks.",
    category: "compare",
  },
  {
    id: "s6",
    label: "Draft a compliant clause",
    prompt: "Draft a compliant payment clause aligned with Malaysian contract law best practice.",
    category: "draft",
  },
  {
    id: "s7",
    label: "Summarise this Act",
    prompt: "Provide a structured summary of this Act with sections, scope and key obligations.",
    category: "research",
  },
  {
    id: "s8",
    label: "Identify employee obligations",
    prompt: "Extract all employee obligations from this employment agreement and explain enforceability.",
    category: "analyse",
  },
];

export const MALAYSIAN_SOURCES: LegalSource[] = [
  {
    id: "src-emp-1955",
    title: "Employment Act 1955",
    type: "act",
    authority: "Federal",
    jurisdiction: "Malaysia",
    area: "Employment",
    section: "Part XI",
    url: "https://www.legislation.gov.my/act-265",
    publishedAt: "1955-01-01",
    excerpt:
      "An Act to provide for the regulation of the terms and conditions of employment of workmen.",
    verified: true,
    relevance: 0.95,
  },
  {
    id: "src-contracts-1950",
    title: "Contracts Act 1950",
    type: "act",
    authority: "Federal",
    jurisdiction: "Malaysia",
    area: "Contract",
    section: "Section 10",
    url: "https://www.legislation.gov.my/act-136",
    publishedAt: "1950-01-01",
    excerpt: "All agreements are contracts if they are made by the free consent of parties.",
    verified: true,
    relevance: 0.9,
  },
  {
    id: "src-pdpa-2010",
    title: "Personal Data Protection Act 2010",
    type: "act",
    authority: "Federal",
    jurisdiction: "Malaysia",
    area: "Data Protection",
    section: "Section 7",
    url: "https://www.pdp.gov.my",
    publishedAt: "2010-06-02",
    excerpt: "General principle: personal data shall not be processed without consent.",
    verified: true,
    relevance: 0.88,
  },
  {
    id: "src-industrial-1967",
    title: "Industrial Relations Act 1967",
    type: "act",
    authority: "Federal",
    jurisdiction: "Malaysia",
    area: "Employment",
    section: "Section 20",
    url: "https://www.legislation.gov.my/act-177",
    publishedAt: "1967-01-01",
    excerpt: "Right to terminate a contract of service.",
    verified: true,
    relevance: 0.8,
  },
  {
    id: "src-cas-emp",
    title: "Sivaguru a/l Siva Subramaniam v Suruhanjaya Perkhidmatan Awam [2023] 1 MLJ 184",
    type: "case",
    authority: "Federal Court",
    jurisdiction: "Malaysia",
    area: "Employment",
    url: "https://elaw.mlaw.gov.my",
    publishedAt: "2023-02-10",
    excerpt: "On procedural fairness in disciplinary proceedings.",
    verified: true,
    relevance: 0.75,
  },
  {
    id: "src-imr-guide",
    title: "Industrial Court Awards: Misconduct Standard",
    type: "guideline",
    authority: "Industrial Court",
    jurisdiction: "Malaysia",
    area: "Employment",
    publishedAt: "2024-01-01",
    excerpt: "Domestic inquiries must follow the principles of natural justice.",
    verified: true,
    relevance: 0.7,
  },
];

export const MOCK_MATTERS: Matter[] = [
  {
    id: "m-1001",
    number: "M-2026-001",
    name: "TechNova Sdn Bhd — Employment Disputes",
    description: "Three pending wrongful termination claims for FY2026.",
    client: "TechNova Sdn Bhd",
    status: "active",
    priority: "high",
    area: "Employment",
    documentsCount: 24,
    conversationsCount: 8,
    tasksCount: 6,
    researchCount: 14,
    updatedAt: isoDaysFromNow(-1),
    classification: "confidential",
  },
  {
    id: "m-1002",
    number: "M-2026-002",
    name: "GreenHostel Compliance Review",
    description: "Annual hostel rules compliance and policy update.",
    client: "GreenHostel Malaysia",
    status: "review",
    priority: "medium",
    area: "Property",
    documentsCount: 12,
    conversationsCount: 5,
    tasksCount: 3,
    researchCount: 9,
    updatedAt: isoDaysFromNow(-3),
    classification: "internal",
  },
  {
    id: "m-1003",
    number: "M-2026-003",
    name: "DataShield — PDPA Audit",
    description: "Cross-border data transfer audit and remediation.",
    client: "DataShield Technologies",
    status: "active",
    priority: "high",
    area: "Data Protection",
    documentsCount: 18,
    conversationsCount: 4,
    tasksCount: 9,
    researchCount: 11,
    updatedAt: isoDaysFromNow(-2),
    classification: "privileged",
  },
  {
    id: "m-1004",
    number: "M-2026-004",
    name: "Acquisition: Valley Foods Sdn Bhd",
    description: "Share purchase agreement review and negotiation.",
    client: "Valley Foods Group",
    status: "pending",
    priority: "medium",
    area: "Corporate",
    documentsCount: 48,
    conversationsCount: 12,
    tasksCount: 7,
    researchCount: 22,
    updatedAt: isoDaysFromNow(-5),
    classification: "privileged",
  },
  {
    id: "m-1005",
    number: "M-2026-005",
    name: "BumiWage Payroll Deduction Policy",
    description: "Salary deduction policy compliance review.",
    client: "BumiWage Sdn Bhd",
    status: "completed",
    priority: "low",
    area: "Employment",
    documentsCount: 6,
    conversationsCount: 3,
    tasksCount: 1,
    researchCount: 4,
    updatedAt: isoDaysFromNow(-12),
    classification: "internal",
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "d-1",
    name: "Employment Agreement — Lim Wei Jian.pdf",
    type: "application/pdf",
    size: 320_000,
    uploadedAt: isoDaysFromNow(-1),
    status: "ready",
    matterId: "m-1001",
    classification: "confidential",
    pageCount: 14,
  },
  {
    id: "d-2",
    name: "Hostel Rules 2026 (Draft).docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 84_000,
    uploadedAt: isoDaysFromNow(-3),
    status: "processing",
    matterId: "m-1002",
    classification: "internal",
    pageCount: 8,
  },
  {
    id: "d-3",
    name: "PDPA Audit Findings.pdf",
    type: "application/pdf",
    size: 540_000,
    uploadedAt: isoDaysFromNow(-2),
    status: "ready",
    matterId: "m-1003",
    classification: "privileged",
    pageCount: 22,
  },
  {
    id: "d-4",
    name: "Share Purchase Agreement — Valley Foods.pdf",
    type: "application/pdf",
    size: 1_240_000,
    uploadedAt: isoDaysFromNow(-5),
    status: "ready",
    matterId: "m-1004",
    classification: "privileged",
    pageCount: 76,
  },
  {
    id: "d-5",
    name: "Warning Letter Draft.docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 24_000,
    uploadedAt: isoDaysFromNow(-7),
    status: "ready",
    matterId: "m-1001",
    classification: "confidential",
    pageCount: 2,
  },
];

export const MOCK_ANALYSIS: DocumentAnalysis = {
  id: "a-1",
  documentId: "d-1",
  status: "complete",
  summary:
    "A standard Malaysian employment agreement with restrictive covenants, IP assignment, and statutory leave entitlements. Several risks identified around termination, non-compete enforceability, and overtime provisions.",
  findings: [
    {
      id: "f1",
      kind: "risk",
      title: "Non-compete may be unenforceable",
      detail:
        "Clause 9 imposes a 24-month non-compete. Such long restrictions are typically unenforceable in Malaysia absent consideration and reasonable scope.",
      severity: "high",
      page: 4,
      recommendation: "Reduce to 12 months and limit geographical scope to Peninsular Malaysia.",
    },
    {
      id: "f2",
      kind: "missing_clause",
      title: "Missing express garden-leave language",
      detail: "No express garden-leave provision; employer may face difficulty placing employee on leave.",
      severity: "medium",
      page: 5,
      recommendation: "Add an express garden-leave clause with full pay.",
    },
    {
      id: "f3",
      kind: "ambiguity",
      title: "Overtime calculation unclear",
      detail: "Section on overtime does not specify rate basis (hourly vs. monthly).",
      severity: "medium",
      page: 6,
    },
    {
      id: "f4",
      kind: "termination",
      title: "Termination-for-cause threshold narrow",
      detail: "Termination-for-cause list excludes wilful disobedience — consider adding.",
      severity: "low",
      page: 7,
    },
    {
      id: "f5",
      kind: "confidentiality",
      title: "Confidentiality survives termination — good",
      detail: "Clause 12 obliges confidentiality for 3 years post-termination.",
      severity: "info",
      page: 8,
    },
    {
      id: "f6",
      kind: "payment",
      title: "Deductions language not aligned with Section 24",
      detail: "Deductions clause may not satisfy Employment Act 1955 s.24 requirements.",
      severity: "high",
      page: 9,
      recommendation: "Align deductions with s.24 written authorisation requirements.",
    },
  ],
  parties: ["TechNova Sdn Bhd (Employer)", "Lim Wei Jian (Employee)"],
  dates: ["2026-01-15 (effective)", "Probation ends 2026-04-15"],
  generatedAt: isoDaysFromNow(-1),
};

export const MOCK_TASKS: LegalTask[] = [
  {
    id: "t-1",
    title: "Draft response to claim letter",
    matterId: "m-1001",
    matterName: "TechNova Sdn Bhd — Employment Disputes",
    assignee: "Aisyah Rahman",
    dueDate: isoDaysFromNow(0),
    priority: "high",
    status: "in_progress",
    notes: "Coordinator requested by 5pm.",
  },
  {
    id: "t-2",
    title: "Schedule client meeting",
    matterId: "m-1003",
    matterName: "DataShield — PDPA Audit",
    assignee: "Aisyah Rahman",
    dueDate: isoDaysFromNow(2),
    priority: "medium",
    status: "todo",
  },
  {
    id: "t-3",
    title: "File affidavit at court",
    matterId: "m-1004",
    matterName: "Acquisition: Valley Foods Sdn Bhd",
    assignee: "Junior Counsel",
    dueDate: isoDaysFromNow(-2),
    priority: "high",
    status: "blocked",
    notes: "Awaiting client signature.",
  },
  {
    id: "t-4",
    title: "Update hostel rules policy",
    matterId: "m-1002",
    matterName: "GreenHostel Compliance Review",
    assignee: "Aisyah Rahman",
    dueDate: isoDaysFromNow(5),
    priority: "low",
    status: "todo",
  },
  {
    id: "t-5",
    title: "Close out completed matter",
    matterId: "m-1005",
    matterName: "BumiWage Payroll Deduction Policy",
    assignee: "Aisyah Rahman",
    dueDate: isoDaysFromNow(7),
    priority: "low",
    status: "todo",
  },
];

export const MOCK_RISKS: RiskItem[] = [
  {
    id: "r1",
    title: "Non-compete clause likely unenforceable",
    description: "24-month post-termination restriction exceeds typical enforceability range.",
    severity: "high",
    category: "Employment",
    matterId: "m-1001",
    documentId: "d-1",
    createdAt: isoDaysFromNow(-1),
  },
  {
    id: "r2",
    title: "Salary deductions not aligned with s.24",
    description: "Written authorisation and itemisation requirements need strengthening.",
    severity: "high",
    category: "Compliance",
    matterId: "m-1001",
    documentId: "d-1",
    createdAt: isoDaysFromNow(-1),
  },
  {
    id: "r3",
    title: "Cross-border data transfer risk",
    description: "Sub-processor list outside Malaysia without explicit PDPA safeguards.",
    severity: "high",
    category: "Documentation",
    matterId: "m-1003",
    documentId: "d-3",
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "r4",
    title: "Hostel curfew may breach tenancy guidance",
    description: "Mandatory curfew may exceed landlord authority under national housing policy.",
    severity: "medium",
    category: "Operational",
    matterId: "m-1002",
    documentId: "d-2",
    createdAt: isoDaysFromNow(-3),
  },
  {
    id: "r5",
    title: "Indemnity cap may be too low",
    description: "Indemnity cap at 25% of contract value may be insufficient for warranty claims.",
    severity: "medium",
    category: "Contractual",
    matterId: "m-1004",
    documentId: "d-4",
    createdAt: isoDaysFromNow(-5),
  },
  {
    id: "r6",
    title: "Missing data retention schedule",
    description: "No documented retention period for processed personal data.",
    severity: "medium",
    category: "Compliance",
    matterId: "m-1003",
    documentId: "d-3",
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "r7",
    title: "Force majeure carve-outs limited",
    description: "Pandemics and cyber events not explicitly listed as triggering events.",
    severity: "low",
    category: "Contractual",
    matterId: "m-1004",
    documentId: "d-4",
    createdAt: isoDaysFromNow(-5),
  },
  {
    id: "r8",
    title: "Overtime calculation ambiguity",
    description: "Overtime calculation basis unclear and may trigger disputes.",
    severity: "low",
    category: "Employment",
    matterId: "m-1001",
    documentId: "d-1",
    createdAt: isoDaysFromNow(-1),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c-1",
    title: "Salary deduction analysis",
    pinned: true,
    createdAt: isoDaysFromNow(-1),
    updatedAt: isoDaysFromNow(0),
    messageCount: 14,
    preview: "Identify lawful deductions under Section 24 of the Employment Act 1955…",
    matterId: "m-1001",
  },
  {
    id: "c-2",
    title: "Hostel rules compliance",
    createdAt: isoDaysFromNow(-3),
    updatedAt: isoDaysFromNow(-1),
    messageCount: 9,
    preview: "Compare proposed hostel rules to current tenancy guidelines…",
    matterId: "m-1002",
  },
  {
    id: "c-3",
    title: "PDPA cross-border transfers",
    createdAt: isoDaysFromNow(-2),
    updatedAt: isoDaysFromNow(-2),
    messageCount: 22,
    preview: "Identify sub-processor risk in cross-border data transfer…",
    matterId: "m-1003",
  },
  {
    id: "c-4",
    title: "Warranty indemnity cap",
    createdAt: isoDaysFromNow(-5),
    updatedAt: isoDaysFromNow(-4),
    messageCount: 6,
    preview: "Draft alternative indemnity cap language…",
    matterId: "m-1004",
  },
  {
    id: "c-5",
    title: "Force majeure carve-outs",
    createdAt: isoDaysFromNow(-6),
    updatedAt: isoDaysFromNow(-5),
    messageCount: 4,
    preview: "Identify gaps in force majeure trigger list…",
    matterId: "m-1004",
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n-1",
    kind: "analysis",
    title: "Document analysis complete",
    body: "Employment Agreement — Lim Wei Jian.pdf analysed: 6 findings (2 high severity).",
    href: "/legalai/documents",
    read: false,
    createdAt: isoDaysFromNow(-1),
  },
  {
    id: "n-2",
    kind: "task",
    title: "Task due today",
    body: "Draft response to claim letter (TechNova Sdn Bhd).",
    href: "/legalai/tasks",
    read: false,
    createdAt: isoDaysFromNow(0),
  },
  {
    id: "n-3",
    kind: "matter",
    title: "Matter updated",
    body: "DataShield — PDPA Audit: 3 new tasks created.",
    href: "/legalai/matters",
    read: true,
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "n-4",
    kind: "research",
    title: "Research saved",
    body: "Employment Act 1955 — Part XI summary saved to Saved Items.",
    href: "/legalai/saved",
    read: true,
    createdAt: isoDaysFromNow(-3),
  },
  {
    id: "n-5",
    kind: "ai",
    title: "AI analysis ready",
    body: "Risk engine flagged 2 new high-risk items on DataShield matter.",
    href: "/legalai/risk",
    read: false,
    createdAt: isoDaysFromNow(-1),
  },
];

export const MOCK_DRAFTS: Draft[] = [
  {
    id: "dr-1",
    title: "Warning Letter — Lim Wei Jian",
    template: "warning_letter",
    body: "Date: 21 August 2026\n\nDear Mr. Lim Wei Jian,\n\nWe write to formally warn you…",
    matterId: "m-1001",
    updatedAt: isoDaysFromNow(-1),
    status: "draft",
  },
  {
    id: "dr-2",
    title: "Hostel Rules 2026",
    template: "hostel_rules",
    body: "1. Quiet hours are from 10.00 pm to 7.00 am…",
    matterId: "m-1002",
    updatedAt: isoDaysFromNow(-2),
    status: "review",
  },
];

export const MOCK_SAVED: SavedItem[] = [
  {
    id: "sv-1",
    kind: "source",
    title: "Employment Act 1955 — Part XI",
    body: "Hours of work, holidays, rest days and overtime provisions.",
    tags: ["Employment", "Statute"],
    savedAt: isoDaysFromNow(-2),
  },
  {
    id: "sv-2",
    kind: "answer",
    title: "When can an employer deduct wages?",
    body: "Only with written authorisation and within limits under s.24…",
    tags: ["Employment", "Deductions"],
    matterId: "m-1001",
    savedAt: isoDaysFromNow(-1),
  },
  {
    id: "sv-3",
    kind: "clause",
    title: "Garden leave clause",
    body: "The Employer may at any time require the Employee to remain away from the workplace…",
    tags: ["Employment", "Clause"],
    savedAt: isoDaysFromNow(-3),
  },
  {
    id: "sv-4",
    kind: "research",
    title: "PDPA cross-border transfers — overview",
    body: "Section 7 + Schedule — Standard of protection equivalency test.",
    tags: ["Data Protection"],
    matterId: "m-1003",
    savedAt: isoDaysFromNow(-2),
  },
];

export const MOCK_ACTIVITY: RecentActivity[] = [
  {
    id: "ac-1",
    kind: "conversation",
    title: "Salary deduction analysis",
    detail: "IRAC analysis · 14 messages",
    href: "/legalai/assistant",
    at: isoDaysFromNow(0),
  },
  {
    id: "ac-2",
    kind: "document",
    title: "Employment Agreement — Lim Wei Jian.pdf",
    detail: "Analysis complete · 6 findings",
    href: "/legalai/documents",
    at: isoDaysFromNow(-1),
  },
  {
    id: "ac-3",
    kind: "research",
    title: "PDPA cross-border transfers",
    detail: "Saved · 4 sources",
    href: "/legalai/research",
    at: isoDaysFromNow(-2),
  },
  {
    id: "ac-4",
    kind: "draft",
    title: "Warning Letter — Lim Wei Jian",
    detail: "Edited · draft",
    href: "/legalai/drafting",
    at: isoDaysFromNow(-1),
  },
  {
    id: "ac-5",
    kind: "matter",
    title: "DataShield — PDPA Audit",
    detail: "3 new tasks · updated",
    href: "/legalai/matters",
    at: isoDaysFromNow(-2),
  },
  {
    id: "ac-6",
    kind: "analysis",
    title: "Risk engine flagged 2 high items",
    detail: "DataShield matter",
    href: "/legalai/risk",
    at: isoDaysFromNow(-1),
  },
];

export const MOCK_USAGE: AIUsage = {
  questionsAsked: 184,
  documentsAnalysed: 36,
  draftsGenerated: 21,
  researchSessions: 92,
};

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  usage: MOCK_USAGE,
  activeMatters: MOCK_MATTERS.filter((m) => m.status === "active").length,
  highPriorityMatters: MOCK_MATTERS.filter((m) => m.priority === "high").length,
  totalDocuments: MOCK_DOCUMENTS.length,
  processingDocuments: MOCK_DOCUMENTS.filter((d) => d.status === "processing").length,
  risks: {
    high: MOCK_RISKS.filter((r) => r.severity === "high").length,
    medium: MOCK_RISKS.filter((r) => r.severity === "medium").length,
    low: MOCK_RISKS.filter((r) => r.severity === "low").length,
  },
  tasks: {
    today: MOCK_TASKS.filter(
      (t) => new Date(t.dueDate ?? now()).toDateString() === new Date().toDateString(),
    ).length,
    overdue: MOCK_TASKS.filter(
      (t) =>
        t.status !== "done" &&
        new Date(t.dueDate ?? now()).getTime() < Date.now(),
    ).length,
    upcoming: MOCK_TASKS.filter((t) => t.status === "todo").length,
  },
};

export const MOCK_SEARCH_RESULTS: ResearchResult[] = [
  {
    source: MALAYSIAN_SOURCES[0]!,
    summary:
      "Part XI covers hours of work, rest days, holidays and overtime. Section 60D limits normal hours of work.",
    citation: "Employment Act 1955 (Act 265), Part XI",
    relevance: 0.95,
    date: "1955",
  },
  {
    source: MALAYSIAN_SOURCES[3]!,
    summary:
      "Section 20 sets out circumstances under which an employer may terminate a contract without notice.",
    citation: "Industrial Relations Act 1967, s.20",
    relevance: 0.85,
    date: "1967",
  },
  {
    source: MALAYSIAN_SOURCES[4]!,
    summary:
      "Federal Court affirms natural justice applies to disciplinary proceedings in the public sector.",
    citation: "[2023] 1 MLJ 184",
    relevance: 0.78,
    date: "2023",
  },
];

export const MOCK_REASONING_STEPS = [
  {
    id: "r-1",
    label: "Searching Malaysian legal sources",
    status: "complete" as const,
    detail: "Indexed 12 statutes and 4 cases.",
  },
  {
    id: "r-2",
    label: "Reviewing relevant provisions",
    status: "complete" as const,
    detail: "Employment Act 1955 — Parts XI, XII",
  },
  {
    id: "r-3",
    label: "Comparing applicable requirements",
    status: "complete" as const,
    detail: "Side-by-side comparison complete.",
  },
  {
    id: "r-4",
    label: "Preparing legal analysis",
    status: "complete" as const,
    detail: "IRAC structure ready.",
  },
];

export const MOCK_TOOL_EXECUTIONS: ToolExecution[] = [
  {
    id: "t-1",
    name: "Search legal sources",
    description: "Retrieved 12 Malaysian statutes and 4 cases.",
    status: "complete",
  },
  {
    id: "t-2",
    name: "Retrieve relevant provisions",
    description: "Fetched sections of Employment Act 1955.",
    status: "complete",
  },
  {
    id: "t-3",
    name: "Analyse uploaded document",
    description: "Extracted parties, obligations and risks.",
    status: "complete",
  },
  {
    id: "t-4",
    name: "Compare clauses",
    description: "Compared clause language to current statute.",
    status: "running",
  },
  {
    id: "t-5",
    name: "Extract obligations",
    description: "Identifying employee and employer obligations.",
    status: "pending",
  },
  {
    id: "t-6",
    name: "Generate answer",
    description: "Composing legal analysis.",
    status: "pending",
  },
];

export const MOCK_INITIAL_MESSAGES: Message[] = [
  {
    id: "m-1",
    role: "user",
    content:
      "Under what circumstances may an employer make deductions from an employee's wages in Malaysia?",
    createdAt: isoDaysFromNow(-1),
  },
  {
    id: "m-2",
    role: "assistant",
    createdAt: isoDaysFromNow(-1),
    content:
      "Under Malaysian law, deductions from an employee's wages are principally regulated by **Section 24 of the Employment Act 1955**.\n\n### Rule\nAn employer may only deduct from wages:\n\n1. With the employee's **written authorisation**; and\n2. For lawful purposes including:\n   - Recovery of **advances or overpayments**;\n   - **Trade union subscriptions** (per the Trade Unions Act 1959);\n   - Payments to a **co-operative society** registered under the Co-operative Societies Act 1993;\n   - **Insurance premiums** under a contract for the employee's benefit.\n\n### Practical implications\n- Deductions for **disciplinary fines** are not permissible under the Act.\n- Employers should retain signed authorisation and itemised records.\n- Total deductions should not reduce wages below lawful minimums.\n\n> Verify against the **Employment (Limitation on Deductions from Wages) Regulations 1980** for the precise list and any amendments.",
    citations: [
      {
        index: 1,
        source: MALAYSIAN_SOURCES[0]!,
      },
    ],
    sources: [MALAYSIAN_SOURCES[0]!],
    reasoningSteps: MOCK_REASONING_STEPS,
    toolExecutions: MOCK_TOOL_EXECUTIONS,
    suggestions: [
      "Draft a compliant deduction authorisation clause",
      "Summarise the deduction regulations 1980",
      "What is the maximum permitted deduction?",
      "Identify related disciplinary risks",
    ],
    verified: true,
    attachments: [],
  },
];

export const JURISDICTIONS: { id: "Malaysia" | "Singapore" | "United Kingdom" | "Other"; label: string }[] = [
  { id: "Malaysia", label: "Malaysia" },
  { id: "Singapore", label: "Singapore" },
  { id: "United Kingdom", label: "United Kingdom" },
  { id: "Other", label: "Other" },
];

export const LEGAL_AREAS: { id: LegalArea; label: string }[] = [
  { id: "Employment", label: "Employment" },
  { id: "Contract", label: "Contract" },
  { id: "Corporate", label: "Corporate" },
  { id: "Compliance", label: "Compliance" },
  { id: "Data Protection", label: "Data Protection" },
  { id: "Property", label: "Property" },
  { id: "Litigation", label: "Litigation" },
  { id: "Other", label: "Other" },
];

export const SOURCE_TYPES: { id: RiskCategory; label: string }[] = [
  { id: "Legal", label: "Statutes" },
  { id: "Compliance", label: "Cases" },
  { id: "Contractual", label: "Guidelines" },
  { id: "Employment", label: "Government" },
  { id: "Financial", label: "Other" },
];

export const DRAFT_TEMPLATES: { id: string; label: string; description: string }[] = [
  { id: "employment_agreement", label: "Employment Agreement", description: "Standard Malaysian employment contract." },
  { id: "warning_letter", label: "Warning Letter", description: "Misconduct / performance warning." },
  { id: "show_cause_letter", label: "Show-Cause Letter", description: "Require written explanation." },
  { id: "company_policy", label: "Company Policy", description: "Internal HR / compliance policy." },
  { id: "hostel_rules", label: "Hostel Rules", description: "Tenant rules and regulations." },
  { id: "property_acknowledgement", label: "Property Acknowledgement", description: "Receipt / acknowledgement." },
  { id: "hr_notice", label: "HR Notice", description: "Notice to all employees." },
  { id: "legal_letter", label: "Legal Letter", description: "Letter to a third party." },
  { id: "contract_clause", label: "Contract Clause", description: "Single clause drafting." },
  { id: "internal_memo", label: "Internal Memo", description: "Internal legal memo." },
  { id: "custom", label: "Custom Document", description: "Start from blank." },
];

export function defaultComposerContext(): ComposerContext {
  return {
    jurisdiction: "Malaysia",
    area: "Employment",
    sourceFilter: ["act", "case", "guideline", "government"],
  };
}