'use client'

import { useCallback, useMemo, useRef, useState } from 'react'
import { Activity, ArrowRight, Bot, Check, CircleHelp, Copy, Download, FileJson, FileText, GitBranch, History, Inbox, ListFilter, Maximize2, MessageSquareText, Moon, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, Play, Plus, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Sun, Trash2, Upload, UserRound, X, Zap } from 'lucide-react'
import { ReactFlow, Background, Controls, Handle, MarkerType, MiniMap, Position, addEdge, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeProps } from '@xyflow/react'
import '@xyflow/react/dist/style.css'

type NodeKind = 'trigger' | 'action' | 'condition' | 'output'
type FlowData = { kind: NodeKind; title: string; description: string; icon: string; accent: string; config: string }
type FlowNode = Node<FlowData>

const starterNodes: FlowNode[] = [
  { id: 'intake', type: 'lawNode', position: { x: 80, y: 180 }, data: { kind: 'trigger', title: 'New client intake', description: 'When a new form is submitted', icon: 'inbox', accent: 'violet', config: 'Intake form submitted' } },
  { id: 'classify', type: 'lawNode', position: { x: 390, y: 180 }, data: { kind: 'action', title: 'Classify matter', description: 'Identify practice area and urgency', icon: 'bot', accent: 'blue', config: 'Use legal classifier' } },
  { id: 'urgent', type: 'lawNode', position: { x: 700, y: 180 }, data: { kind: 'condition', title: 'Is this urgent?', description: 'Route matters by urgency', icon: 'branch', accent: 'amber', config: 'Urgency is high' } },
  { id: 'notify', type: 'lawNode', position: { x: 1010, y: 70 }, data: { kind: 'action', title: 'Notify attorney', description: 'Send a priority alert to the team', icon: 'message', accent: 'pink', config: 'Send to matter owner' } },
  { id: 'followup', type: 'lawNode', position: { x: 1010, y: 290 }, data: { kind: 'action', title: 'Create follow-up', description: 'Schedule a response task', icon: 'clock', accent: 'cyan', config: 'Due in 2 business days' } },
  { id: 'matter', type: 'lawNode', position: { x: 1320, y: 180 }, data: { kind: 'output', title: 'Create matter', description: 'Save the intake in your workspace', icon: 'file', accent: 'green', config: 'Create new matter' } },
] as FlowNode[]
const starterEdges: Edge[] = (
  [['intake','classify'],['classify','urgent'],['urgent','notify'],['urgent','followup'],['notify','matter'],['followup','matter']] as Array<[string, string]>
).map(([source, target], i) => ({
  id: `e${i}`,
  source,
  target,
  type: 'smoothstep',
  animated: i === 1,
  markerEnd: { type: MarkerType.ArrowClosed, color: '#7582a1' },
})) as Edge[]
const palette: Array<[NodeKind, string, string, string, string]> = [
  ['trigger','5 Years — The Litigator','Courtroom mechanics and file management','violet','Phases'], ['action','10 Years — The Strategist','Outcome prediction and narrative craft','blue','Phases'], ['condition','15 Years — The Counselor','Bet-the-company litigation leadership','amber','Phases'], ['output','20+ Years — The Rainmaker','Business development and legacy','green','Phases'],
  ['action','Legal Research','Find authority and precedent','blue','Core Skills'], ['action','Case Management','Organize matters and deadlines','cyan','Core Skills'], ['action','Legal Writing','Craft persuasive documents','pink','Core Skills'], ['condition','Deposition','Prepare and examine witnesses','amber','Trial Skills'], ['condition','Courtroom','Lead the hearing or trial','violet','Trial Skills'], ['condition','Cross-Examination','Test testimony under pressure','pink','Trial Skills'], ['condition','Risk Assessment','Evaluate exposure and outcomes','amber','Strategy Skills'], ['condition','Judicial Psychology','Read the room and decision makers','blue','Strategy Skills'], ['condition','Crisis Management','Stabilize high-stakes moments','pink','Strategy Skills'], ['action','Mentoring','Develop the next generation','cyan','Leadership Skills'], ['action','Business Development','Build trusted client relationships','green','Leadership Skills'], ['action','Legacy Building','Create institutional knowledge','violet','Leadership Skills'],
]
const templates: Array<{ name: string; description: string; nodes: FlowNode[]; edges: Edge[] }> = [
  { name: 'Client intake', description: 'Route new matters from intake to ownership.', nodes: starterNodes, edges: starterEdges },
  { name: 'Skill assessment', description: 'Map skills, gaps, and next career steps.', nodes: starterNodes.map((node, index) => ({ ...node, data: { ...node.data, title: ['Skill inventory', 'Gap analysis', 'Priority review', 'Mentor review', 'Career plan', 'Next milestone'][index] ?? node.data.title } })), edges: starterEdges },
  { name: 'Trial preparation', description: 'Organize research, witnesses, and courtroom readiness.', nodes: starterNodes.map((node, index) => ({ ...node, data: { ...node.data, title: ['Matter opened', 'Research authority', 'Ready for trial?', 'Prepare witnesses', 'Build exhibits', 'Trial brief'][index] ?? node.data.title } })), edges: starterEdges },
]
const iconMap: Record<string, typeof Inbox> = { inbox: Inbox, bot: Bot, branch: GitBranch, message: MessageSquareText, clock: Activity, file: FileText }

function LawNode({ data, selected }: NodeProps<FlowNode>) {
  const Icon = iconMap[data.icon] ?? FileJson
  return <div className={`flow-node ${data.accent} ${selected ? 'selected' : ''}`}><Handle type="target" position={Position.Left} /><span className="node-type">{data.kind}</span><span className={`node-icon ${data.accent}`}><Icon size={17} /></span><span className="node-copy"><strong>{data.title}</strong><small>{data.description}</small></span><span className="grip">⋮⋮</span><Handle type="source" position={Position.Right} /></div>
}
const nodeTypes = { lawNode: LawNode }

export default function Page() {
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>(starterNodes)
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>(starterEdges)
  const [selectedId, setSelectedId] = useState('classify'), [paletteOpen, setPaletteOpen] = useState(true), [inspectorOpen, setInspectorOpen] = useState(true), [logOpen, setLogOpen] = useState(false), [aiOpen, setAiOpen] = useState(true), [dark, setDark] = useState(true), [aiBusy, setAiBusy] = useState(false), [aiResult, setAiResult] = useState('Select an AI Element to analyze this career workflow.'), [workspaceMode, setWorkspaceMode] = useState<'library' | 'properties' | 'templates'>('library')
  const [events, setEvents] = useState(['Workflow loaded', 'Selected “Classify matter”', 'Ready to build'])
  const fileInput = useRef<HTMLInputElement>(null)
  const selected = nodes.find((node) => node.id === selectedId)
  const record = (message: string) => setEvents((current: string[]) => [message, ...current].slice(0, 8))
  const onConnect = useCallback((connection: Connection) => { setEdges((current: Edge[]) => addEdge({ ...connection, type: 'smoothstep', animated: true, markerEnd: { type: MarkerType.ArrowClosed, color: '#9c8cff' } }, current)); record('Connected workflow steps') }, [setEdges])
  const onNodeClick = useCallback((_: any, node: FlowNode) => { setSelectedId(node.id); record(`Selected “${node.data.title}”`) }, [])
  const updateSelected = (patch: Partial<FlowData>) => setNodes((current: FlowNode[]) => current.map((node: FlowNode) => node.id === selectedId ? { ...node, data: { ...node.data, ...patch } } : node))
  const addNode = (kind: NodeKind, title: string, description: string, accent: string) => { const id = `${kind}-${Date.now()}`; const node: FlowNode = { id, type: 'lawNode', position: { x: 240 + (nodes.length % 3) * 280, y: 480 + Math.floor(nodes.length / 3) * 160 }, data: { kind, title, description, icon: kind === 'trigger' ? 'inbox' : kind === 'condition' ? 'branch' : kind === 'output' ? 'file' : 'bot', accent, config: 'Configure this step' } }; setNodes((current: FlowNode[]) => [...current, node]); setSelectedId(id); record(`Added “${title}”`) }
  const duplicate = () => { if (!selected) return; const copy = { ...selected, id: `${selected.id}-copy-${Date.now()}`, position: { x: selected.position.x + 50, y: selected.position.y + 50 }, data: { ...selected.data, title: `${selected.data.title} copy` } }; setNodes((current: FlowNode[]) => [...current, copy]); setSelectedId(copy.id); record(`Duplicated “${selected.data.title}”`) }
  const remove = () => { if (!selected) return; setNodes((current: FlowNode[]) => current.filter((node: FlowNode) => node.id !== selected.id)); setEdges((current: Edge[]) => current.filter((edge: Edge) => edge.source !== selected.id && edge.target !== selected.id)); setSelectedId(''); record(`Deleted “${selected.data.title}”`) }
  const reset = () => { setNodes(starterNodes); setEdges(starterEdges); setSelectedId('classify'); record('Reset workflow') }
  const exportFlow = () => { const blob = new Blob([JSON.stringify({ nodes, edges }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'lawflow-workflow.json'; a.click(); record('Exported workflow JSON') }
  const importFlow = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); setNodes(parsed.nodes ?? parsed); setEdges(parsed.edges ?? []); record('Imported workflow JSON') } catch { record('Import failed: invalid JSON') } }; reader.readAsText(file) }
  const applyTemplate = (template: typeof templates[number]) => { setNodes(template.nodes.map((node: FlowNode) => ({ ...node, position: { ...node.position } }))); setEdges(template.edges.map((edge: Edge) => ({ ...edge }))); setSelectedId(template.nodes[1]?.id ?? template.nodes[0]?.id ?? ''); record(`Loaded template “${template.name}”`); setWorkspaceMode('properties') }
  const runAi = async (intent: string) => { setAiBusy(true); setAiResult('Lawmate AI is analyzing your workflow…'); try { const response = await fetch('/api/ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ intent, nodes }) }); const data = await response.json(); setAiResult(data.text); record(`AI completed: ${intent}`) } catch { setAiResult('AI is temporarily unavailable.') } finally { setAiBusy(false) } }

  return <main className={`lawmate-app ${dark ? 'theme-dark' : 'theme-light'}`}><header className="topbar"><div className="brand"><div className="brand-mark"><ShieldCheck size={17} /></div><span>lawmate</span><span className="crumb">/</span><span className="workflow-name">Client intake automation</span></div><div className="top-actions"><span className="saved"><Check size={14} /> Saved just now</span><button className="icon-button" aria-label="Help"><CircleHelp size={16} /></button><button className="avatar">AM</button></div></header>
  <div className="toolbar"><div className="toolbar-group"><button className="toolbar-button primary" onClick={() => record('Test run started')}><Play size={14} fill="currentColor" /> Test run</button><button className="toolbar-button" onClick={reset}><RefreshCw size={14} /> Reset</button></div><div className="toolbar-group"><button className="toolbar-button" onClick={exportFlow}><Download size={14} /> Export</button><button className="toolbar-button" onClick={() => fileInput.current?.click()}><Upload size={14} /> Import</button><input ref={fileInput} type="file" accept="application/json" hidden onChange={importFlow} /></div><div className="toolbar-spacer" /><div className="toolbar-group"><button className={`toolbar-button ai-toggle ${aiOpen ? 'active' : ''}`} onClick={() => setAiOpen((v) => !v)}><Sparkles size={14} /> AI Elements</button><button className="icon-button" onClick={() => setDark((v) => !v)} aria-label="Toggle theme">{dark ? <Sun size={15} /> : <Moon size={15} />}</button><button className="icon-button" onClick={() => setPaletteOpen((v) => !v)} aria-label="Toggle palette">{paletteOpen ? <PanelLeftClose size={15} /> : <PanelLeftOpen size={15} />}</button><button className="icon-button" onClick={() => setInspectorOpen((v) => !v)} aria-label="Toggle inspector">{inspectorOpen ? <PanelRightClose size={15} /> : <PanelRightOpen size={15} />}</button><button className="icon-button" onClick={() => setLogOpen((v) => !v)} aria-label="Toggle event log"><Activity size={15} /></button></div></div>
  <div className="workspace">{paletteOpen && <aside className="left-panel"><div className="panel-tabs" role="tablist" aria-label="Workspace sections"><button className={workspaceMode === 'library' ? 'active' : ''} onClick={() => setWorkspaceMode('library')} role="tab" aria-selected={workspaceMode === 'library'}><ListFilter size={14} /> Library</button><button className={workspaceMode === 'templates' ? 'active' : ''} onClick={() => setWorkspaceMode('templates')} role="tab" aria-selected={workspaceMode === 'templates'}><FileJson size={14} /> Templates</button></div>{workspaceMode === 'library' && <><div className="panel-heading"><div><div className="eyebrow">Build</div><h2>Lawyers</h2></div><Search size={15} /></div><div className="search-box"><Search size={14} /><span>Search lawyers</span><kbd>/</kbd></div>{['Phases','Core Skills','Trial Skills','Strategy Skills','Leadership Skills'].map((category) => <div className="palette-section" key={category}><div className="section-label">{category}</div>{palette.filter((item) => item[4] === category).map(([kind, title, description, accent]) => <button className="palette-item" key={title} onClick={() => addNode(kind, title, description, accent)}><span className={`palette-icon ${accent}`}><Sparkles size={16} /></span><span><strong>{title}</strong><small>{description}</small></span><Plus className="palette-plus" size={15} /></button>)}</div>)}</>}{workspaceMode === 'templates' && <div className="template-library"><div className="panel-heading"><div><div className="eyebrow">Start faster</div><h2>Templates</h2></div><FileJson size={15} /></div><p className="panel-intro">Choose a workflow foundation and customize it in Properties.</p>{templates.map((template) => <button className="template-card" key={template.name} onClick={() => applyTemplate(template)}><span className="template-preview"><span /><span /><span /></span><span><strong>{template.name}</strong><small>{template.description}</small></span><ArrowRight size={14} /></button>)}</div>}</aside>}
  <section className="canvas-shell"><div className="canvas-header"><div><div className="eyebrow">Workflow canvas</div><h1>Client intake automation</h1></div><div className="canvas-meta"><span className="live-dot" /> Draft <span className="divider" /> {nodes.length} steps</div></div><div className="canvas flow-canvas"><ReactFlow nodes={nodes.map((node) => ({ ...node, selected: node.id === selectedId }))} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={onNodeClick} onPaneClick={() => setSelectedId('')} nodeTypes={nodeTypes} defaultViewport={{ x: 30, y: 30, zoom: 0.55 }} colorMode={dark ? 'dark' : 'light'}><Background color={dark ? '#263149' : '#d8dee9'} gap={22} size={1} /><MiniMap nodeColor={(node: FlowNode) => String((node.data as FlowData)?.accent ?? '#7582a1')} pannable zoomable /><Controls showInteractive /></ReactFlow>{logOpen && <div className="event-log"><strong>Event log</strong>{events.map((event, index) => <div key={`${event}-${index}`}>{event}</div>)}</div>}</div></section>
  {inspectorOpen && <aside className="right-panel"><div className="panel-tabs" role="tablist" aria-label="Properties section"><button className={workspaceMode === 'properties' ? 'active' : ''} onClick={() => setWorkspaceMode('properties')} role="tab" aria-selected={workspaceMode === 'properties'}><Settings2 size={14} /> Properties</button></div><div className="panel-heading"><div><div className="eyebrow">Configure</div><h2>Step details</h2></div><button className="icon-button" onClick={() => setInspectorOpen(false)}><X size={15} /></button></div>{selected ? <><div className="selected-summary"><span className={`palette-icon ${selected.data.accent}`}><Settings2 size={16} /></span><div><strong>{selected.data.title}</strong><small>{selected.data.kind} step</small></div></div><label className="field-label">Name<input value={selected.data.title} onChange={(event) => updateSelected({ title: event.target.value })} /></label><label className="field-label">Description<textarea value={selected.data.description} onChange={(event) => updateSelected({ description: event.target.value })} rows={3} /></label><div className="inspector-actions"><button className="secondary-button" onClick={duplicate}><Copy size={14} /> Duplicate</button><button className="danger-button" onClick={remove}><Trash2 size={14} /> Delete</button></div></> : <div className="empty-inspector"><Maximize2 size={20} /><p>Select or connect a step on the canvas.</p></div>}</aside>}</div>
  {aiOpen && <section className="ai-elements" aria-label="Lawmate AI Elements"><div className="ai-heading"><div><div className="eyebrow">Vercel AI Elements</div><h2>Career intelligence</h2></div><span className="ai-pulse"><Sparkles size={13} /> Live</span></div><p className="ai-intro">Use intelligent suggestions to shape stronger lawyer career workflows.</p><div className="ai-actions"><button onClick={() => runAi('intelligent node recommendations')} disabled={aiBusy}><Bot size={14} /> Recommend nodes</button><button onClick={() => runAi('automated layout suggestions')} disabled={aiBusy}><Maximize2 size={14} /> Optimize layout</button><button onClick={() => runAi('skill gap analysis')} disabled={aiBusy}><Activity size={14} /> Analyze skill gaps</button><button onClick={() => runAi('career path optimization')} disabled={aiBusy}><ArrowRight size={14} /> Optimize path</button><button onClick={() => runAi('smart edge animation suggestions')} disabled={aiBusy}><Zap size={14} /> Suggest edge motion</button></div><div className="ai-result"><Sparkles size={15} /><span>{aiResult}</span></div></section>}
  <footer className="statusbar"><span><span className="status-dot" /> All systems operational</span><span>v0.4.2 <span className="divider" /> Documentation <ArrowRight size={12} /></span></footer></main>
}

function MousePointerIcon() { return <div className="empty-icon"><Maximize2 size={20} /></div> }
